dist: trusty
sudo: false
language: cpp

branches:
# whitelist
    only:
        - master
# blacklist
    except:
        - wip

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

before_script:
    # Nothing to do

script:
    - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 ./compile.sh

deploy:
    provider: script
    skip_cleanup: true
    script: curl -T build/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udgolgovsky:$BINTRAY_API_KEY "https://api.bintray.com/content/dgolgovsky/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

after_success:
    # Sending data to codecov.io
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
